Fix ci.yml to run all bandit commands within Docker container

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,16 +15,15 @@ jobs:
           docker compose run --rm web pytest
       - name: Run Bandit security scan
         run: |
-          docker compose run --rm web bandit -r . -q -ll --exclude ./tests --exit.zero || {
-            echo "Bandit found  potential security issues."
-            echo "Scanning for medium and high severity issues that should fail the pipeline."
+          docker compose run --rm web bash -c "bandit -r . -q -ll --exclude ./tests --exit-zero || {
+            echo 'Bandit found potential security issues.'
+            echo 'Scanning for medium and high severity issues that should fail the pipeline.'
             bandit -r . --exclude ./tests --level medium --confidence medium --format custom --output ./.bandit_report.json
-            if [ -s ./.bandit_report.json ]
-            then
+            if [ -s ./.bandit_report.json ]; then
               cat ./.bandit_report.json
               exit 1
             fi
-          }
+          }" 
       - name: Run OWASP Dependency Check
         run: |
           docker pull owasp/dependency-check:latest
